### ISSUE TITLE
[suggestion] Exclude preprints (10.1101/$) from the newly introduced '-r' option

### ISSUE THREAD

**Issue by Adafede** [egonw/ons-wikidata#7]
I think this should be safe and avoid the creation of preprints.

There is probably a better way to do it but this is what comes to my mind for now

**Comment by egonw** [comment]
I like that idea.

**Comment by Adafede** [comment]
Or also something like *rxiv ?

**Comment by Adafede** [comment]
And also `10.21203` (ResearchSquare)

**Comment by egonw** [comment]
I have created this PR but cannot test it today (I will try next weekend). But this way you can play with it: https://github.com/egonw/ons-wikidata/pull/9 (plz let me know if you find something weird).

**Comment by Adafede** [comment]
Thank you!

Tried some cases an got a 

```
Caught: groovy.lang.MissingPropertyException: No such property: option for class: quickstatements
groovy.lang.MissingPropertyException: No such property: option for class: quickstatements
	at quickstatements$_run_closure2$_closure9.doCall(quickstatements.groovy:221)
	at quickstatements$_run_closure2.doCall(quickstatements.groovy:220)
	at quickstatements.run(quickstatements.groovy:219)
```

**Comment by egonw** [comment]
@Adafede, okay, I pushed a fix.

**Comment by Adafede** [comment]
Couldn't push myself because of rights but it works now! Thank you for the quick fix!

I also added:
```
        // check if the DOI is from a (recognized) preprint server
        if (!(
          it.contains("rxiv") || // any Rxiv # added
          it.contains("RXIV") || // any Rxiv # added
          it.startsWith("10.1101") || // bioRxiv
          it.startsWith("10.21203"))) // ResearchSquare
          out.println it
```
