### ISSUE TITLE
list of DOIs that cannot be handled because of response length

### ISSUE THREAD

**Issue by Adafede** [egonw/ons-wikidata#8]
When trying to import citation data on highly cited (Nobel-related) scientific articles, some of them have such a long list the script fails.

I do not really know where to store this so opening a thread here (I'll update the list as I encounter them)...

- 10.1126/SCIENCE.1102896 (47,621 citing DOIs)
- 10.2307/1912352 (14,780 citing DOIs)

@csisc

**Comment by egonw** [comment]
I added a check in the code that will skip articles with more then 10,000 citations. Those will have to be handled with other tools.
